### ISSUE TITLE
Can't easily import this module

### ISSUE THREAD

**Issue by snoopyjc** [arshadkazmi42/currency-symbols#14]
This module has a '-' in it's name, so the only way to import it is to:

    import importlib
    currency_symbols = importlib.import_module('currency-symbols')

**Comment by arshadkazmi42** [comment]
Is it. I never thought this is a problem in python import.
We should get this fixed. Would you like to take a try on this?

**Comment by loricvdt** [comment]
I'm also having issues importing it. I just replaced the dash in the directory name of the module by an underscore to fix it. I'm making a pull request to fix it (hopefully), it should then be updated on pip

**Comment by ilya1200** [comment]
Also having troubles with importing.
Would be great to have that fixed.

**Comment by loricvdt** [comment]
@ilya1200 my PR should solve the issue, you can try it out and see if it does the trick

**Comment by arshadkazmi42** [comment]
This is deployed v2.0.0 @loricvdt @ilya1200 can you try this now.

**Comment by loricvdt** [comment]
Works great thanks!
(tested on Windows Python 3.9.0 and Ubuntu Python 3.6.9)

**Comment by arshadkazmi42** [comment]
Awesome. 
Closing this issue.
