### ISSUE TITLE
Change github workflow to run on pull requests

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/currency-symbols#31]
Change this line 

https://github.com/arshadkazmi42/currency-symbols/blob/master/.github/workflows/pytest.yml#L3 

similar to these lines

https://github.com/gh-conf/rhof/blob/master/.github/workflows/nodejs.yml#L3-L5

**Comment by Amank-root** [comment]
Hi @arshadkazmi42 , I am interested in working with you. Could you assign it to me?

**Comment by arshadkazmi42** [comment]
Assigned
